mapleland-backServer/src/main/java/org/mapleLand/maplelanbackserver/init/monster/AquariumMonsterDataInitializer.java, mapleland-backServer/src/main/java/org/mapleLand/maplelanbackserver/init/monster/ElnathMonsterDataInitializer.java, mapleland-backServer/src/main/java/org/mapleLand/maplelanbackserver/init/monster/LeafreMonsterDataInitializer.java, mapleland-backServer/src/main/java/org/mapleLand/maplelanbackserver/init/monster/LudibriumMonsterDataInitializer.java, mapleland-backServer/src/main/java/org/mapleLand/maplelanbackserver/init/monster/OrbisMonsterDataInitializer.java, mapleland-backServer/src/main/java/org/mapleLand/maplelanbackserver/init/monster/VictoryMonsterDataInitializer.java
=> feat: 몬스터 드랍 아이템 8개로 추가

frontend/index.html, frontend/src/shared/ui/layouts/header/HeaderLogo.tsx
=> refactor:타이틀 메샵에서 메랜샵으로 변경으로 인한 리팩토링

frontend/src/feature/trade/ui/TradeCard.tsx
=> fix: item.iscompleted일땐 에딧버튼 안뜨게 수정

backend/src/main/java/org/mapleland/maplelanbackserver/service/MapService.java, backend/src/main/java/org/mapleland/maplelanbackserver/table/Jari.java, frontend/src/feature/trade/ui/TradeCard.tsx
=> release: main -> deploy (자리 업데이트 기능 수정)

backend/src/main/java/org/mapleland/maplelanbackserver/init/DummyDataInitializer.java, frontend/src/feature/report/hooks/useReportDialog.ts
신고 이미지 제한을 10mb로 제한
신고 이미지 제한을 10mb로 제한
이슈번호, 관련 링크 등
=> 신고 이미지 제한을 10mb로 제한한 것을 메인에서 디플로이로 머지

frontend/src/feature/report/hooks/useReportDialog.ts
=> fix: 신고 이미지 올릴떄 이미지 파일인지 확인

backend/src/main/java/org/mapleland/maplelanbackserver/config/WebSocketConfig.java
=> fix: backend websocket 부분 수정

frontend/.env
=> fix: .env파일 수정

frontend/package-lock.json, frontend/package.json
=> fix: date-fns-tz 설치 안된부분 설치

frontend/src/feature/trade/ui/TradeCardHeader.tsx
=> fix: 생성시간관련 보완 작업

frontend/index.html, frontend/src/feature/trade/ui/TradeBadges.tsx, frontend/src/feature/trade/ui/TradeCardHeader.tsx
=> 메인에서 파비콘 문제 해결한것 디플로이 브랜치에도 머지

frontend/index.html, frontend/src/feature/price/ui/PriceChart.tsx
=> 프라이스 통계타임 UTC로 보이던것 KR시간으로 변경한거 메인에서 디플로이로 머지

frontend/src/feature/trade/ui/TradeBadges.tsx, frontend/src/feature/trade/ui/TradeCard.tsx
=> fix: 트레이드벳지 부분 아래 간격 안맞는거 수정

frontend/src/feature/price/ui/PriceChart.tsx, frontend/src/feature/trade/ui/TradeBadges.tsx, frontend/src/feature/trade/ui/TradeCard.tsx
=> 트레이드벳지 부분 아래 간격 안맞는거 수정

frontend/src/feature/alert/ui/AlertMapSection.tsx, frontend/src/feature/popularJari/ui/PopularJariList.tsx, frontend/src/feature/trade/ui/TradeSection.tsx
=> style: 프론트엔드 스타일 변경

frontend/src/feature/register/ui/RegisterNoticeBox.tsx, frontend/src/feature/trade/ui/TradeSection.tsx
=> 자리등록 로직 변경으로 인해 registernoticebox 문구 수정 및 머지

frontend/src/entity/map/hooks/useAllMaps.ts, frontend/src/shared/lib/getInitials.ts, frontend/src/shared/lib/isSubsequence.ts, frontend/src/shared/ui/search/hooks/useSearchSuggestions.ts
초성입력시에도 검색 자동완성 되는 기능 구현을 했습니다.
사용자가 `죽숲` 또는 `ㅈㅅ`만 입력해도 `죽은나무숲`이 자동완성 리스트에 나타납니다.
초성만으로도 순서 기반으로 유사 매칭이 됩니다.
close #102
=> feat: 초성입력시에도 검색 자동완성 되는 기능 구현

frontend/src/entity/jari/hooks/usePopularJari.ts
=> refactor: popularJari staleTime → refetchInterval로 변경

frontend/src/entity/jari/hooks/usePopularJari.ts
=> refactor : usePopularJari에 staleTime도 추가

frontend/src/feature/jari/ui/JariMiniMapCard.tsx
Link가 있어야 할부분에 button이 있는것 수정
button에 aschild를 써서 버튼 스타일을 유지하며 Link로 뜨게 수정
close #113
=> refactor : Link가 있어야 할부분에 button이 있는것 수정

frontend/src/feature/price/ui/PriceChart.tsx, frontend/src/feature/price/ui/PriceStatInfo.tsx
=> refactor: price부분 뒤죽박죽이던 rounded sm으로 통일

frontend/src/feature/jari/ui/JariMiniMapCard.tsx, frontend/src/feature/price/ui/PriceChart.tsx, frontend/src/feature/price/ui/PriceStatInfo.tsx
=> refactor: price부분 뒤죽박죽이던 rounded sm으로 통일 및 머지

frontend/src/feature/price/ui/PriceChart.tsx
가격 차트의 숫자 단위를 한국식 화폐 표기(만, 억 등)로 변경하여 가독성 개선하였습니다.
close #119
=> refactor : 가격 차트의 숫자 단위를 한국식 화폐 표기(만, 억 등)로 변경하여 가독성 개선

backend/src/main/java/org/mapleland/maplelanbackserver/controller/admincontroller/AdminController.java, backend/src/main/java/org/mapleland/maplelanbackserver/dto/Map/JariResponse.java, backend/src/main/java/org/mapleland/maplelanbackserver/dto/response/JariListResponse.java, backend/src/main/java/org/mapleland/maplelanbackserver/service/MapService.java, frontend/src/feature/report/api/submitReport.ts
=> release: main -> deploy (모든 자리 조회 API 추가)

frontend/src/entity/jari/api/getAdminJari.ts, frontend/src/entity/jari/api/getJariList.ts, frontend/src/feature/trade/hooks/useTradeCard.ts, frontend/src/feature/trade/ui/TradeCard.tsx, frontend/src/feature/trade/ui/TradeCardHeader.tsx, frontend/src/page/admin/Dashboard.tsx
어드민페이지 자리표시 기능 추가
어드민페이지에 최신 자리 10개씩 표시
close #132
=> feat: 어드민페이지 자리표시 기능 추가

backend/src/main/java/org/mapleland/maplelanbackserver/service/MapService.java, backend/src/main/java/org/mapleland/maplelanbackserver/table/Jari.java
현재 IQR 계산을 생성시간 기준으로 하기에 혼란을 빚고있습니다.
이를 수정했습니다.
생성시간 기준 -> 수정시간 기준
This closes #144
=> feat: IQR 계산을 수정시간 기준으로 하도록 변경

frontend/src/page/admin/AllUsers.tsx, frontend/src/page/jari/Detail.tsx, frontend/src/shared/ui/search/hooks/useSearchSuggestions.ts
allusers페이지에서 utc시간으로 나오는거 한국시간으로 변경
UTC 시간에서 9시간 다시 차이나게 해서 한국시간으로 표시
close #162
=> refactor: allusers페이지에서 utc시간으로 나오는거 한국시간으로 변경

frontend/src/feature/user/ui/UserProfileCard.tsx
=> refactor: profile페이지에서 utc시간으로 나오는거 한국시간으로 변경

frontend/src/feature/ban/ui/UserBannedCard.tsx, frontend/src/feature/user/ui/UserStatsChart.tsx, frontend/src/page/admin/AllUsers.tsx, frontend/src/page/admin/ReportDetail.tsx
refactor: UTCㅡ>KT로 안바꾼 부분들 싹다 바꿈
아직 고치지 않은 부분들이 있었는데 다 고침
이슈번호, 관련 링크 등
=> refactor: UTCㅡ>KT로 안바꾼 부분들 싹다 바꿈

frontend/src/app/router/router.tsx, frontend/src/feature/ban/ui/UserBannedCard.tsx, frontend/src/feature/notice/ui/NoticeBanner.tsx, frontend/src/feature/trade/ui/CompletedTradeBox.tsx, frontend/src/feature/user/ui/UserWelcomeBox.tsx, frontend/src/page/Event.tsx, frontend/src/page/Home.tsx, frontend/src/shared/ui/layouts/footer/Footer.tsx
NoticeBanner를 공지사항 안내에서 이벤트 공지로 변경
close #166
=> NoticeBanner를 공지사항 안내에서 이벤트 공지로 변경

backend/src/main/java/org/mapleland/maplelanbackserver/config/SecurityConfiguration.java, backend/src/main/java/org/mapleland/maplelanbackserver/controller/SseController.java, backend/src/main/java/org/mapleland/maplelanbackserver/dto/jari/JariCompletedEvent.java, backend/src/main/java/org/mapleland/maplelanbackserver/filter/AdminCheckFilter.java, backend/src/main/java/org/mapleland/maplelanbackserver/service/JariSseBroadCaster.java, backend/src/main/java/org/mapleland/maplelanbackserver/service/MapService.java
=> release: main -> deploy (실시간 거래 현황 제공 SSE)

frontend/src/feature/jari/ui/EditJariPopover.tsx, frontend/src/feature/trade/hooks/useTradeCard.ts, frontend/src/feature/trade/ui/CompletedTradeBox.tsx, frontend/src/feature/trade/ui/TradeCard.tsx
=> fix: 거래 완료 시 전역 상태로 최신 거래 반영되도록 수정

backend/src/main/java/org/mapleland/maplelanbackserver/config/SecurityConfiguration.java
* hotfix: `/api/jari/recent` 시큐리티 허용
=> release: main -> deploy (hotfix: `/api/jari/recent` 시큐리티 허용)

frontend/src/feature/trade/ui/CompletedTradeBox.tsx
=> style: 거래완료 부분 추가

frontend/src/feature/trade/ui/CompletedTradeBox.tsx
=> release : deploy ㅡ> main (style변화)

backend/src/main/java/org/mapleland/maplelanbackserver/service/MapService.java
* hotfix: 최근 완료 거래 글 조회 3개 -> 10개 변경
=> release: main -> deploy (hotfix: 최근 완료 거래 글 조회 3개 -> 10개 변경)

backend/src/main/java/org/mapleland/maplelanbackserver/service/MapService.java
=> release : deploy ㅡ> main (completedTradeBox stlye 변경)

frontend/src/shared/ui/search/SearchInputWithSuggestions.tsx
검색어 입력창에서 방향키(↑↓)와 Enter 키로 추천 목록을 선택할 수 있는 기능을 추가했습니다.
- Input에 키보드 이벤트 핸들러 추가
- 방향키(ArrowUp, ArrowDown)로 리스트 탐색 가능
- Enter 키로 현재 포커싱된 추천 항목 선택
- 선택 시 input 초기화 및 추천 리스트 닫힘
- focusedIndex 기본값은 -1 (포커싱되지 않은 상태)
- handleSelect 내부에서 입력값 초기화, 추천 목록 제거, 포커스 인덱스 초기화 수행
close #204
=> feat: 검색 제안 목록에서 방향키 및 엔터로 항목 선택 기능 추가

frontend/src/feature/notice/ui/AlertBanner.tsx, frontend/src/page/Home.tsx
=> feat : alertBanner 만듦

frontend/src/page/Home.tsx
=> release : main ㅡ> deploy

frontend/src/app/router/router.tsx, frontend/src/feature/admin/ui/UserCard.tsx, frontend/src/feature/report/api/getUserReports.ts, frontend/src/feature/report/hooks/useUserReports.ts, frontend/src/feature/report/model/type.ts, frontend/src/page/admin/UserReports.tsx
유저목록페이지에서 그 유저의 리포트내역을 볼수있는 버튼 추가 및 리포트페이지 추가
-close #231
=> feat: 유저 리포트 페이지 구현

frontend/src/feature/trade/ui/CompletedTradeBox.tsx
=> chore: 컴플리티드 배너 5초에서 3초 간격으로 변하는걸로 변경

frontend/src/app/router/router.tsx
=> fix: event-page 경로 수정으로 인한 커밋

frontend/src/app/router/router.tsx, frontend/src/entity/trade/api/getCompletedTradeCount.ts, frontend/src/feature/trade/ui/TradeStatsChart.tsx, frontend/src/feature/worldJari/ui/WorldInfoPanel.tsx, frontend/src/page/admin/Dashboard.tsx, frontend/src/page/admin/TradeStats.tsx
=> feat: trade-stats페이지 만들었음
